#! /bin/bash 

if [[ -z $1 ]] ;then
	echo "This script need at least one valid distro version passed as param"
	echo ""
	echo "Usage example:"
	echo "$0 [0.0.1] [0.1.2] ... [x.x.x] "
	exit;
fi

function validate() {
for VALID_DISTRO_VERSION in "$@";
do
	if [[ $detected_distro_version == $VALID_DISTRO_VERSION ]]; then
		DETECTED_VALID_DISTRO_VERSION=$detected_distro_version;
		break
	fi 
done


if [[ -z $DETECTED_VALID_DISTRO_VERSION  ]]
then
      echo "Unable to determinate your Distro version or the given one \"$detected_distro_version\" is not among the valid distro names." 
      echo "Valid distro versions are:"
      for name in "$@"; do echo "$name"; done
      echo ""
      read -p "Please type one of the versions from the above list to select it: " detected_distro_version
      validate $@

else
      echo "$DETECTED_VALID_DISTRO_VERSION has been selected as your installation distro version"
fi

}

detected_distro_version=$(lsb_release -r | cut -f 2)
validate $@
export DETECTED_VALID_DISTRO_VERSION




