#! /bin/bash 

if [[ -z $1 ]] ;then
	echo "This script check if the first pased argument string match with any of the rest passed string value arguments"
	echo "In order to work "
	echo ""
	echo "Usage example:"
	echo "$0 [needle] [value-1] ... [value-n] "
	exit;
fi

function validate() {
valid_iteration=false;
for valid_value in "$@";
do

	if [[ $valid_iteration == false ]]; then
		$valid_iteration=true 
		if [[ $detected_value == $valid_value ]]; then
			VALUE_IN_ARGS=$detected_value;
			break
		fi 
	fi
done


if [[ -z $VALUE_IN_ARGS  ]]
then
      echo "the given value \"$detected_value\" is not among valid elements." 
      echo "Valid option elements are:"
      for name in "$@"; do echo "$name"; done
      echo ""
      read -p "Please type one of the elements from the above list to select it: " detected_value
      validate $@

else
      echo "$VALUE_IN_ARGS has been selected."
fi


}


detected_value=$1
validate $@
export VALUE_IN_ARGS




